### ISSUE TITLE
Impossible to build

### ISSUE THREAD

**Issue by HideakiAtsuyo** [luccanunes/discord.cpp#4]
https://i.imgur.com/8ycyNf1.png
2 external unresolved

**Comment by HideakiAtsuyo** [comment]
2 external unresolved

**Comment by HideakiAtsuyo** [comment]
2 external unresolved

**Comment by luccanunes** [comment]
As I will point out in the README.md file on future commits, to create your project using discord.cpp you have to follow these steps (Visual Studio):

- Create your solution
- Add a source file 
- Add the compiler include path:
To starting using discord.cpp and all its features, you first have to tell your IDE/compiler where you're importing it from.
Here's how to do it in Visual Studio:
1. Right click your *project* name and select properties
![image](https://user-images.githubusercontent.com/68504851/97646641-f66ba680-1a2e-11eb-809b-b263b8428130.png)
2. Select "C/C++"
3. Click "Additional Include Directories", selected the small arrow on the right and click "Edit"
![image](https://user-images.githubusercontent.com/68504851/97646811-67ab5980-1a2f-11eb-8667-ec9e1b6b135e.png)
4. Click the new folder icon and then the three dots to starting browsing your file explorer.
![image](https://user-images.githubusercontent.com/68504851/97646868-9cb7ac00-1a2f-11eb-9527-26ea2df19536.png)
5. Select the "/src" folder in the directory that you installed discord.cpp
6. Click "Ok" and "Apply".
- Add the linker path:
Now that you've added the include path, the compiler is able to find all the classes and functions declarations, but not really their definitions. For that, we need to include an additional depencie to the linker.
Here's how to do it in Visual Studio:
1. Follow step 1 of "Add the compiler include path"
2. Select "Linker"
3. Click "Additional Library Directories", selected the small arrow on the right and click "Edit"
![image](https://user-images.githubusercontent.com/68504851/97648131-c32b1680-1a32-11eb-9dfb-ff97f34e4ff4.png)
4. Click the new folder icon and then the three dots to starting browsing your file explorer.
![image](https://user-images.githubusercontent.com/68504851/97648199-ebb31080-1a32-11eb-9218-9ed4a5e83a98.png)
5. Select the "/src/Release" folder in the directory that you installed discord.cpp
6. Click "Ok" and "Apply".
7. Now, go to the "Input" tab, still in the linker properties
8. Select "Additional Dependencies", and edit the text string by adding "discord-cpp.lib;" to its beginning
![image](https://user-images.githubusercontent.com/68504851/97648393-62500e00-1a33-11eb-8eba-45eed1fcd837.png)
9. Hit "Apply" and "Ok" and you should be good to go.

**Comment by luccanunes** [comment]
All the steps in the previous comment should work starting from the next commit i make, where i'll add the "Release" folder.

**Comment by HideakiAtsuyo** [comment]
It is impossible to use it without the build?

Because i tried to directly use the folder to avoid the usage of .lib

**Comment by luccanunes** [comment]
Well, I guess you could use Visual Studio's "Add existing file" option and manually add all the .cpp files. That wouldn't make a copy of the file, just keep a reference to it, therefore adding the funcions and classes definitions, but i don't think that's a really good idea.
Any special reason not to use .lib?

**Comment by HideakiAtsuyo** [comment]
At the moment for this project yes, there is no sln file we need to recreate the project and compile it with the files :D

**Comment by HideakiAtsuyo** [comment]
When i add the files https://i.imgur.com/uM4Eaee.png

**Comment by luccanunes** [comment]
You still need to include the `dpp.h` file, because it contains all the declarations

**Comment by HideakiAtsuyo** [comment]
https://i.imgur.com/7trgzDj.png
https://i.imgur.com/yz6anb8.png

Thanks ! Tell me when the .lib is in the release 😄

**Comment by HideakiAtsuyo** [comment]
https://i.imgur.com/7gCy9FD.png

But i have a suggestion: Add a "debug" option to avoid a lot of logs

message.reply doesn't work :(

**Comment by luccanunes** [comment]
Amazing !! I sure will.
Tip: 
If you wish to get rid of the relative paths ("../dpp/dpp.h")  you could add it to your compile include path.
I am aware of the excessive logging xD, i'll remove it from the main branch and add it to a developmente one.
Thanks for contribuiting!!

**Comment by luccanunes** [comment]
Do you get any errors?

**Comment by HideakiAtsuyo** [comment]
Oh sorry just a bug, it work :)

**Comment by HideakiAtsuyo** [comment]
> 
> 
> Amazing !! I sure will.
> Tip:
> If you wish to get rid of the relative paths ("../dpp/dpp.h") you could add it to your compile include path.
> I am aware of the excessive logging xD, i'll remove it from the main branch and add it to a developmente one.
> Thanks for contribuiting!!

good idea later i will contribute more i like this project

**Comment by luccanunes** [comment]
Huge thaaanks!!

**Comment by luccanunes** [comment]
Update: just pushed the Release folder to GitHub, following the steps I mentioned should work in order to link all files

**Comment by luccanunes** [comment]
> It is impossible to use it without the build?
> 
> Because i tried to directly use the folder to avoid the usage of .lib

Hey there!! Greate news.
Now discord.cpp is also available as a header-only library!!!
Its hosted at the `header-only` branch. Check the README.md to learn how to use it.
Please report any bugs that you might find!!
